### ISSUE TITLE
[REQUEST] Recent sections

### ISSUE THREAD

**Issue by Higtzy** [Paperback-iOS/app#140] opened 2020-05-16 14:36 UTC
Description
Having a recent tab, showing the history or recent mangas that you are reading.

How would it improve the App?
It is easy to go look back and continue reading mangas that are currently being read rather than manually type it on or scroll threw the following tab when you have many mangas that are listed as follows tab.

![Recent-1](https://user-images.githubusercontent.com/65337728/82122339-07ff1180-9761-11ea-8e1d-6e76ad99e9d6.jpg)

**Comment by AgreeToMyTerms** [comment] 2020-05-16 14:46
Dupe of #99

**Closed** 2020-05-20 17:30 UTC
Labels: enhancement
