### ISSUE TITLE
[REQUEST] Add badge showing number of unread chapters 

### ISSUE THREAD

**Issue by VanThien33** [Paperback-iOS/app#525] opened 2022-04-02 14:43 UTC
**Description**
Even though there are badges showing updated chapters, after reading even one chapter the badge disappears.
As the title says, this badge will show how many unread chapter of a title.

**How would it improve the App?**
For users with many titles in the library, it would be very useful for them to comeback later and know which title still have unread chapters. Users will no longer need to open the title to check which is actually time-consuming considering the amount of titles they have in the library.

**Comment by TheNetsky** [comment] 2022-04-02 16:11
Please read the other issues first before opening
Dupe of https://github.com/Paperback-iOS/app/issues/416 and https://github.com/Paperback-iOS/app/issues/387

**Closed** 2022-04-03 18:15 UTC
Labels: enhancement
