### ISSUE TITLE
[REQUEST] sync history between devices

### ISSUE THREAD

**Issue by Drfroggyjr** [Paperback-iOS/app#648] opened 2022-07-27 04:49 UTC
Trying to use the app between iPhone, iPad, and Mac has become increasingly hard having to send backups every time.
**How would it improve the App?**
I think it would make the app more appealing and user friendly.

maybe I can pull from iCloud if there are no servers.

**Comment by TheNetsky** [comment] 2022-07-29 18:54
Dupe of https://github.com/Paperback-iOS/app/issues/423

**Closed by TheNetsky** 2022-07-29 18:54 UTC
Labels: enhancement
