### ISSUE TITLE
[REQUEST] All Downloaded Manga Tab

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#318] opened 2021-04-06 16:28 UTC
**Description**
Atab that shows all downloaded manga.

**How would it improve the App?**
It would let me easily delete downloads from chapters that I have read without having to scroll through all of my manga.

**Comment by FaizanDurrani** [comment] 2021-04-06 17:06
Duplicate of #283

**Closed by FaizanDurrani** 2021-04-06 17:06 UTC
Labels: enhancement
