### ISSUE TITLE
[REQUEST] Instant Search alternate sources from manga description page

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#443] opened 2022-01-01 05:30 UTC
**Description**
A clear description of the feature

Ability to click a button on a manga page that will take its name and start a source search for alternatives that you can toggle a tap to merge on instead of manual search and one by one merge

**How would it improve the App?**
How would the feature improve the app?

So currently you have to perform a search and manually click each source tap merge and then search you library to merge. This will allow a 2 part solution, 1 when you search you only need to bookmark one the. From that description page launch a search to merge since you already on the target manga to merge to you don't need to search what to merge to and just to a multi select to merge all the different ones into that manga

2 if you have a bookmark and are looking for alternative sources you can just tap to launch the search and select what you want to merge from available sources that have it

**Additional context**

So this auto search will work similar to the trackers where you tap and it auto starts a search with the name in the search field

So button here
![image](https://user-images.githubusercontent.com/5268461/147844550-d2a15bd4-59a6-41dd-937d-22a39195d545.jpeg)

Which would trigger a view

![image](https://user-images.githubusercontent.com/5268461/147844555-d8ac6009-4f37-42d5-ac51-e4864d1852b3.png)

In which you can select one or more from the sources and merge them in bulk

**Comment by FaizanDurrani** [comment] 2022-01-02 09:38
Duplicate of #427

**Closed by FaizanDurrani** 2022-01-02 09:38 UTC
Labels: enhancement

**Comment by XenitXTD** [comment] 2022-01-02 09:56
@FaizanDurrani this is not intended to migrate but rather to trigger an instant search to find more sources to merge quickly

**Comment by FaizanDurrani** [comment] 2022-01-02 10:00
It’s the same thing

**Comment by FaizanDurrani** [comment] 2022-01-02 10:02
The single title migration will be implemented within the title view as a button

**Comment by XenitXTD** [comment] 2022-01-02 10:11
Will wait and see then
