### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by DottyPottyLotty** [Paperback-iOS/app#284] opened 2021-03-27 02:56 UTC
**Description**
A number count of how many unread chapters and how many new chapters has been added since the last update. Or a tab for latest update.

**How would it improve the App?**
It would be a good way to know which manga has the latest update

**Comment by ConradWeiser** [comment] 2021-03-28 03:01
Duplicate of https://github.com/Paperback-iOS/app/issues/274

**Closed by ConradWeiser** 2021-03-28 03:01 UTC
Labels: duplicate, enhancement
