### ISSUE TITLE
[REQUEST] Showing unread chapters as badge

### ISSUE THREAD

**Issue by Zixtar** [Paperback-iOS/app#274] opened 2021-03-18 08:31 UTC
**Description**
The badge showing the number of updated chapters would show the number of all unread chapters. There could be a toggle in the settings between the two behaviours.

**How would it improve the App?**
I have mangas in my library that I am planning to read or with which I have not read up to the last chapter, for me it would be a lot more useful to have a badge showing how many chapters are not read instead of how many have been updated.

**Comment by FaizanDurrani** [comment] 2022-04-03 18:17
Duplicate of #123

**Closed by FaizanDurrani** 2022-04-03 18:17 UTC
Labels: enhancement
