### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by pandeynmn** [Paperback-iOS/app#269] opened 2021-03-14 18:07 UTC
**Description**
Copy to clipboard feature: In the Manga details page, an option to press and hold the Manga Title to copy the title to clip board

**How would it improve the App?**
It will make it easier to search that particular manga in search tab to find additional sorces for that manga, additionally another function could be created which gives out some sort of context menu upon clicking the title of the Manga in Manga Details page opens a menu which has an option to **"search this manga for other sources"** (_searches the title string in search tab for other sources_)

**Additional context**
It would make it easier for users to search other sources of a manga without having to type out the title of the manga again.

**Comment by ConradWeiser** [comment] 2021-05-14 06:23
Duplicate of https://github.com/Paperback-iOS/app/issues/344
While this issue is older, It doesn’t have a proper title nor do I have permissions to change it.

Thus I’m marking this as the dupe since the other shows in searches better

**Closed by ConradWeiser** 2021-05-14 06:23 UTC
Labels: enhancement
