### ISSUE TITLE
[REQUEST] Show followed mangas in search page

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#380] opened 2021-07-20 05:05 UTC
**Description**
In the search menu, mangas that are already in our library should have a marker. This would look like the "downloaded chapters" marker but be on the bottom left and have no number.

**How would it improve the App?**
It would be much easier to consume new manga without repeatedly opening up existing mangas.

**Comment by Akiawa** [comment] 2021-07-21 01:18
Duplicate of : https://github.com/Paperback-iOS/app/issues/122

**Closed** 2022-04-13 16:26 UTC
Labels: enhancement
