### ISSUE TITLE
Search Bar Suggestion 

### ISSUE THREAD

**Issue by Sukicchi** [Paperback-iOS/app#136] opened 2020-05-11 19:43 UTC
It would make it easier to find Mangas if example I type “d” then all mangas with letter d come out then I continue with “d e m o n” then all mangas whit demon on title show up.

**Comment by AgreeToMyTerms** [comment] 2020-05-11 19:46
Dupe of #19?

**Comment by Sukicchi** [comment] 2020-05-11 19:50
AgreeToMyTerms Ya sorry didnt see the closed section this is my first time using GitHub. What does the closed section mean?

**Comment by AgreeToMyTerms** [comment] 2020-05-11 20:29
Feel free to close the issue.

**Comment by FaizanDurrani** [comment] 2020-09-22 17:56
Functionality by design

**Closed by FaizanDurrani** 2020-09-22 17:56 UTC
Labels: enhancement
