### ISSUE TITLE
Constant conflict message

### ISSUE THREAD

**Issue by Microscale** [Paperback-iOS/app#105] opened 2020-04-29 12:50 UTC
When closing and then opening the app I get a conflict message saying I have manga in different lists although I have list syncing enabled and I clicked on use local.
https://youtu.be/PpA6qeCt5o0 

I am using the latest public build: v0.2.1-r1
It’s annoying because I have to do the same thing every time I refresh my app. It would help if we could remember this to avoid annoyance 😅

**Comment by Microscale** [comment] 2020-05-02 01:48
The same thing started happening with the “manga not followed on mangadex” message and keeps asking me to upload to mangadex or unfollow locally even though I keep pressing upload to mangadex 

It just won’t sync and save.. can’t read manga without it popping up a few times.

**Comment by FaizanDurrani** [comment] 2020-05-02 01:52
Can you send me your MDList link in Discord DM, Paper#1932

**Comment by FaizanDurrani** [comment] 2020-05-03 00:20
Marking this as resolved since this was an odd anomaly and not really reproducible reliably

**Closed by FaizanDurrani** 2020-05-03 00:20 UTC
Labels: bug
