### ISSUE TITLE
[REQUEST] Display manga cover as faded in search if the manga is in library 

### ISSUE THREAD

**Issue by DishankJ** [Paperback-iOS/app#301] opened 2021-04-01 05:48 UTC
**Description**
Exactly what the title says, the manga cover could have a dark overlay or something similar.

**How would it improve the App?**
To be able to easily differentiate what manga is in library when searching.

**Comment by FaizanDurrani** [comment] 2023-04-07 10:01
Duplicate of #122

**Closed by FaizanDurrani** 2023-04-07 10:01 UTC
Labels: enhancement
