### ISSUE TITLE
[REQUEST] keep last position after selecting a manga during searching/viewing latest updates

### ISSUE THREAD

**Issue by stan-snf** [Paperback-iOS/app#120] opened 2020-05-04 16:19 UTC
**Description**
When searching/viewing latest updates, when clicking on a manga, when you click back, the app should keep your last position (may it be search results or where u were when u were scrolling through latest updates). currently it just returns you to the top, which is kind of annoying.

**How would it improve the App?**
Improves ease of use when browsing latest updates or when searching

**Additional context**
I will add additional context on request if the description is not enough.

**Comment by FaizanDurrani** [comment] 2020-05-20 17:41
Duplicate of #108

**Closed by FaizanDurrani** 2020-05-20 17:41 UTC
Labels: enhancement
