### ISSUE TITLE
[BUG] New Search Completely Frozen When Switching Source

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#321] opened 2021-04-08 03:32 UTC
**Describe the bug**
The search box is completely Frozen and nothing works.

**To Reproduce**
1. Search in "all"
2. Change source
3. Try to edit th search queru

**Expected behaviour**
The search bar to be responsive

**App Version**
Eg: v0.5.0-1.0.6

**Screenshots**
![image](https://user-images.githubusercontent.com/13932583/113964467-8fca9000-97f9-11eb-9da7-ac2f89c97ab2.png)

**Comment by Akiawa** [comment] 2021-04-09 15:07
I can't reproduce this.

**Comment by PythonCoderAS** [comment] 2021-04-09 15:09
> I can't reproduce this.

It was an one-off glitch for me as well. I think it was from rotating from landscape to portrait and then quickly switching source right after.

**Comment by PythonCoderAS** [comment] 2021-04-11 23:37
> I can't reproduce this. 

I found the root cause. If I switch search as an error toast shows up, it freezes both old and new search until I force restart.

**Comment by FaizanDurrani** [comment] 2021-09-01 02:45
Fixed in 0.6.0 (2.0.2-Beta)

**Closed by FaizanDurrani** 2021-09-01 02:45 UTC
Labels: bug
