### ISSUE TITLE
[REQUEST] New sort by category

### ISSUE THREAD

**Issue by superjuice1202** [Paperback-iOS/app#654] opened 2022-08-14 01:04 UTC
**Description**
A new sort by category that allows you to sort by either chapters read or unread.

**How would it improve the App?**
Would make  catching up to manga's so much easier.

**Additional context**
N/A

**Comment by xOnlyFadi** [comment] 2022-08-14 04:49
already was suggested in #383 #386

**Comment by FaizanDurrani** [comment] 2023-04-07 10:05
Duplicate of #383

**Closed by FaizanDurrani** 2023-04-07 10:05 UTC
Labels: enhancement
