### ISSUE TITLE
Discovery search

### ISSUE THREAD

**Issue by haloking4629** [Paperback-iOS/app#212] opened 2021-01-10 18:15 UTC
Whenever I search something on the discovery doesn’t doesn’t appear

**Comment by ConradWeiser** [comment] 2021-01-10 18:28
I’m going to need some more details than that, I cannot reproduce the problem with the description you’ve given me. I suspect this issue can be fixed with some action on you, the users side.

I recommend that if possible, you join our discord channel. If you describe your issue in the support channel, we’d be happy to have a dialog with you to get things patched up.
If this isn’t possible, please reopen an issue with more information.

thanks!

**Closed by ConradWeiser** 2021-01-10 18:28 UTC
