### ISSUE TITLE
[REQUEST] New sort order: Unread chapters

### ISSUE THREAD

**Issue by tejassharma96** [Paperback-iOS/app#386] opened 2021-08-13 19:00 UTC
**Description**
A new sort order that sorts your library by the number of chapters remaining in the manga

**How would it improve the App?**
It would help with discoverability if you have a lot of manga in your library. Sorting on the number of remaining chapters gives you an easy way to bubble your unread manga to the top, and also give you an idea of how much reading you have in store when starting a new manga. I’m making the transition from android to ios and this is my default sorting order for the reasons stated above. it also helps me see when a manga I’m reading has a new chapter, but that’s secondary to the discovery aspect since we already have the "last updated" sort order.

**Comment by ImOldGregg** [comment] 2022-04-10 22:41
Would also like this feature implemented.

**Comment by FaizanDurrani** [comment] 2023-04-07 10:05
Duplicate of #383

**Closed by FaizanDurrani** 2023-04-07 10:05 UTC
Labels: enhancement
