### ISSUE TITLE
[REQUEST] Backup to include tracking

### ISSUE THREAD

**Issue by Samk19** [Paperback-iOS/app#650] opened 2022-07-29 15:13 UTC
**Description**
Enable tracking when restoring title through backup file

**How would it improve the App?**
How would the feature improve the app?
It will improve the backup n restore process.
It is a hassle to re-enable tracking if we have many titles.

**Additional context**
N/A

**Comment by FaizanDurrani** [comment] 2022-07-29 18:53
duplicate of #469

**Comment by TheNetsky** [comment] 2022-07-29 18:53
Dupe of https://github.com/Paperback-iOS/app/issues/469

**Closed** 2022-07-29 18:53 UTC
Labels: enhancement
