### ISSUE TITLE
[REQUEST] Set Reading Direction and Mode per Collection or per Manga

### ISSUE THREAD

**Issue by ZeroHart** [Paperback-iOS/app#497] opened 2022-02-21 22:17 UTC
Description:
By Collection, Select Reading Direction and mode for all elements under a Collection
By Manga, Ber able to select the Reading Direction and Mode per Manga Basis, always defaulting to whatever you have in main settings

How would this improve the app?
 Be able to have collections to separate Manga, Webtoons and Comics.  Making it easier to swap from reading one tyope to the next without going crazy on what was the correct direction.

**Comment by TheNetsky** [comment] 2022-02-22 10:53
Dupe of https://github.com/Paperback-iOS/app/issues/267
Please read the other issues first before creating a new one.

**Closed** 2022-03-09 14:53 UTC
