### ISSUE TITLE
[REQUEST] Allow Custom Thumbnails 

### ISSUE THREAD

**Issue by rishabh139** [Paperback-iOS/app#625] opened 2022-06-28 13:27 UTC
**Description**
Some sources can have distorted thumbnails. It would be great to have the option to use a custom thumbnail.

**How would it improve the App?**
QOL

**Comment by TheNetsky** [comment] 2022-07-29 18:59
Dupe of https://github.com/Paperback-iOS/app/issues/381

**Closed by TheNetsky** 2022-07-29 18:59 UTC
Labels: enhancement
