### ISSUE TITLE
[BUG] New Reader skips chapter on exit

### ISSUE THREAD

**Issue by rintendou** [Paperback-iOS/app#488] opened 2022-02-09 22:11 UTC
**Describe the bug**
Upon finishing and exiting a manga with the new reader of 0.7, incorrectly doing so will result in one chapter being skipped.

**To Reproduce**
[Use vertical orientation] Go to the end of a manga chapter (ex: 60) and let the next chapter load in (70). Once the next chapter has loaded in, scroll down until go to page 1 or 2 and then exit the manga/app, the next time you open up that manga, you’ll begin at the beginning of the next chapter (71).

**Expected behaviour**
Upon returning to the manga, I expected to return to the beginning of the chapter left off at at, instead of the following chapter.

**App Version**
0.7

**Screenshots**
Screen recording attached.

**Comment by FaizanDurrani** [comment] 2022-02-10 03:36
No screen recording is attached, can you upload it again

**Comment by rintendou** [comment] 2022-02-10 11:26
Sorry about that, mobile Github web browser sucks. 

https://user-images.githubusercontent.com/83848755/153398522-e6a472d2-7953-42b2-9734-32068c3c509a.MOV

**Comment by FaizanDurrani** [comment] 2022-02-10 11:29
Is this consistently reproducible?

**Comment by rintendou** [comment] 2022-02-10 11:44
Yes, it can be done on any manga, as long as it's on the new reader.

**Comment by rintendou** [comment] 2022-02-12 04:03
Update: Works only on downloaded manga. I tried this on a manga I didn't download, which is rare for me, and it was working normally.

**Comment by FaizanDurrani** [comment] 2022-03-23 14:57
Is this still a issue in the latest build?

**Comment by FaizanDurrani** [comment] 2022-04-20 22:33
closing because of no update

**Closed by FaizanDurrani** 2022-04-20 22:33 UTC
Labels: bug
