### ISSUE TITLE
[REQUEST] Option to sort by "last read" in collections

### ISSUE THREAD

**Issue by andrea11564** [Paperback-iOS/app#421] opened 2021-11-29 16:01 UTC
Is it possible to add an option to sort for last read manga for each collection?
The only last read filtering is quite annoying as it works globally, even for manga I opened once and are not even in my colletions.
![497267E6-FFBB-49F5-A5EA-EB3F8063CFE5](https://user-images.githubusercontent.com/79382170/143900571-3cd00ded-cca1-4e3f-b215-41b17c5b967d.jpeg)

**Comment by MFlynny86** [comment] 2021-12-15 10:19
I second this

**Comment by FaizanDurrani** [comment] 2022-01-02 09:47
Duplicate of #383

**Closed by FaizanDurrani** 2022-01-02 09:47 UTC
Labels: enhancement
