### ISSUE TITLE
[REQUEST] Resume Reading Button/Recently Read Section

### ISSUE THREAD

**Issue by stummyhurt** [Paperback-iOS/app#128] opened 2020-05-06 18:55 UTC
**Description**
A section where the app lists recently read manga and has a resume button where you can easily pick up where you left off in reading.

**How would it improve the App?**
Saves time trying to find the next chapter to read.

**Additional context**
In Tachiyomi for Android, there's a section labeled "History" where you can find all of your recently read manga and tap resume to pick up where you left off. Heres a screenshot: 
![Screenshot_20200506-135118](https://user-images.githubusercontent.com/25081475/81216813-287cde00-8fa1-11ea-8a4a-7be0a3c5bdb5.jpg)

**Comment by FaizanDurrani** [comment] 2020-05-06 19:27
Duplicate of #91 and #61

**Closed** 2020-05-06 19:27 UTC
Labels: duplicate, enhancement
