### ISSUE TITLE
[REQUEST] Page-reload button

### ISSUE THREAD

**Issue by CherryPie94** [Paperback-iOS/app#125] opened 2020-05-05 11:45 UTC
**Description**
Can we get a page-reload button that would allow us to reload the image (when it refuses to download and we get a blue X) instead of existing the chapter and opening it again?

**Comment by HellDuke-Astaroth** [comment] 2020-05-16 14:55
If you scroll past the image a bit and come back, the page will reload.

**Comment by FaizanDurrani** [comment] 2020-05-20 17:52
Duplicate of #95

**Closed by FaizanDurrani** 2020-05-20 17:52 UTC
Labels: enhancement
