### ISSUE TITLE
[REQUEST] Automatic queue when download failed.

### ISSUE THREAD

**Issue by captainnemo-06** [Paperback-iOS/app#379] opened 2021-07-18 01:44 UTC
**Description**
Download automatically queue again a failed download and don't restart the downloaded parts.

**How would it improve the App?**
When a download failed in the current app, it will automatically remove the chapter in the queue. Sometimes it's a hassle to redo the process of downloading again so when it is automatic users won't click download again just to download the failed ones.

**Additional context**
Example is when a chapter has downloaded at least 50% of the chapter then it failed when restarting the download it download again from the start in the current app. It will be better if the app can start again from the 50% that have been downloaded.

**Comment by Akiawa** [comment] 2021-07-19 23:41
Duplicate of : https://github.com/Paperback-iOS/app/issues/241

**Closed** 2022-04-13 16:26 UTC
Labels: enhancement
