### ISSUE TITLE
[REQUEST] Unread chapter count in Library

### ISSUE THREAD

**Issue by DishankJ** [Paperback-iOS/app#343] opened 2021-05-12 16:08 UTC
**Description**
Unread chapters count over manga cover.

**How would it improve the App?**
Ability to quickly check/see unread chapters

**Comment by ConradWeiser** [comment] 2021-05-12 16:29
Duplicate of https://github.com/Paperback-iOS/app/issues/274, this feature already has a open request!

**Closed by ConradWeiser** 2021-05-12 16:29 UTC
Labels: duplicate, enhancement
