### ISSUE TITLE
[REQUEST] Show an icon on bookmarked series in the discover and search lists

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/app#367] opened 2021-07-06 15:43 UTC
**Description**
It would be really nice if I could see at a glance whether a search result or discover result is in my library, without having to open up the item. Having a bookmark icon or some other indicator over the thumbnail would make it a lot easier. 

**How would it improve the App?**
When looking for new series, it would be much easier to tell if I already added one without opening each one up one by one to check. 

**Additional context**

**Comment by Akiawa** [comment] 2021-07-21 02:36
A bit of a duplicate of : https://github.com/Paperback-iOS/app/issues/122

Re-requested at: https://github.com/Paperback-iOS/app/issues/380

**Closed** 2021-08-18 21:29 UTC
Labels: enhancement
