### ISSUE TITLE
Separation Of Pages (Scrolling downwards) And Info while reading the manga

### ISSUE THREAD

**Issue by Sukicchi** [Paperback-iOS/app#135] opened 2020-05-11 19:37 UTC
I use the scrolling when reading manga and it gets confusing if there is no separation between two pages. (It just looks like the whole manga is 1 page) maybe adding a black horizontal line after each page would help. Also while scrolling down you can put like tiny notifications to show that you are reading a new chapter. Like MR if you scroll from chapter 1 to 2 it shows “New Chapter” on a black text box.

**Comment by ConradWeiser** [comment] 2020-05-29 04:14
Dupe of #113

**Comment by FaizanDurrani** [comment] 2020-11-13 11:28
Option to add padding between pages added in experimental reader

**Closed by FaizanDurrani** 2020-11-13 11:28 UTC
Labels: enhancement
