### ISSUE TITLE
[REQUEST] Display badges for unread chapters

### ISSUE THREAD

**Issue by tejassharma96** [Paperback-iOS/app#387] opened 2021-08-13 19:19 UTC
**Description**
Currently you can see badges for (I think - it isn't super clear what triggers the visibility of the badge) number of updated chapters in your library. I'd like to be able to see the number of unread chapters as a badge generally (even if I just added the manga to my library)

**How would it improve the App?**
It'd be an easy and convenient way to visually see the number of remaining chapters for each manga without actually having to click into the manga and then click "all chapters".

**Comment by FaizanDurrani** [comment] 2022-04-03 18:17
Duplicate of #123

**Closed by FaizanDurrani** 2022-04-03 18:17 UTC
Labels: enhancement
